### ISSUE TITLE
comments not saving to JSON/CSV from checkplotserver

### ISSUE THREAD

**Issue by joshuawallace** [waqasbhatti/astrobase#49] opened 2018-04-13 20:29 UTC
The comments I record in the checkplot server are not getting saved to the JSON checkplotlist, neither are they present in the JSON or CSV file I can download directly from the checkplot server.  The comments do get saved to the pickle files though.  I don't know if this is the intended behavior, I wanted to bring it up in case it isn't.

**Comment by waqasbhatti** [comment] 2018-04-13 21:05
This was intended behavior, but I think you're right that they should be saved to the CSV/JSON as well.

Will fix this in a bit.

**Comment by waqasbhatti** [comment] 2018-04-13 22:38
Looked into this.

Apparently, the comments *were* intended to be exported to CSV/JSON via the checkplotserver UI and written back to the checkplot list JSON. There was a typo preventing this. Now should be fixed. You may need to run through the checkplots in the checkplotserver to make sure the comments get written back to the checkplot list JSON and exported correctly.

**Closed** 2018-05-08 18:27 UTC
Labels: bug
